# Generated by Django 6.1.1 on 2026-09-16 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('stretching', 'Stretching')], default='strength', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LoggedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('stretching', 'Stretching')], default='strength', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('actual_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('actual_weight_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_distance_unit', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='km', max_length=2)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('routine_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.routineexercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workoutlog')),
            ],
        ),
    ]
