# Generated by Django 6.1.1 on 2026-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='km', max_length=2),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2),
        ),
    ]
